apiVersion: v1
kind: Secret
metadata:
  name: order-processing-secret
  namespace: order-processing
  labels:
    app.kubernetes.io/name: order-processing
    app.kubernetes.io/component: app
type: Opaque
stringData:
  DB_PASSWORD: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME_WITH_A_32_BYTE_MINIMUM_RANDOM_SECRET"
  RABBITMQ_PASSWORD: "REPLACE_ME"
